### ISSUE TITLE
Requête API via Insomnia

### ISSUE THREAD

**Issue by vincentferraro** [ouivalo/Rejoindre-notre-equipe-tech#1]
Bonjour,
Je souhaiterais effectuer une requête POST via Insomnia, cela dit, je n'aurais pas besoin de créer un repo GitHub. Est ce possible ou préférez vous que je crée un petit formulaire permettant d'envoyer les informations à l'API? 
Merci. 
Vincent

**Comment by KevinHamonApp** [comment]
Bonjour,
Une requête POST via Insomnia permet de valider uniquement une étape parmi les 5 proposées dans le défi.

**Comment by KevinHamonApp** [comment]
Bonjour,
Utiliser Insomnia ne propose qu'une réponse partielle au défi. En effet, le défi propose les étapes suivantes : 

1.     Pour cela, tu peux utiliser le framework de ton choix (front ou back)
2.     Développer un projet à l'intérieur d'un conteneur (Docker par exemple)
3.     Créer un formulaire proposant les champs nécessaires à l'envoi de données
4.     Au submit du formulaire, envoyer les données à l'API 
5.     Mettre tout cela sur un repo Git à nous partager

Ta proposition répond partiellement à l'étape 4, en envoyant les données à l'API, sans réagir à un formulaire.
