### ISSUE TITLE
Réponse API

### ISSUE THREAD

**Issue by vincentferraro** [ouivalo/Rejoindre-notre-equipe-tech#2]
Bonjour, 
Que doit répondre l'API lorsque la requête est valide? 
Lorsque j'effectue la requête je reçois ça: Response {type: 'opaque', url: '', redirected: false, status: 0, ok: false, …}
L'API ne m'a pas retourné d'erreur.

Merci

**Comment by KevinHamonApp** [comment]
Bonjour,
L'API renvoit en cas d'erreur un document HTML présentant l'erreur. 
Dans le cas d'un succès, elle vous renvoit un message de succès. 
La réponse que vous avez reçue n'est pas la réponse renvoyée par notre API. 

Si vous souhaitez plus d'éléments, pouvez-vous nous partager des informations sur la requête réalisée et sur l'erreur complète ?

**Comment by vincentferraro** [comment]
Bonjour, 
Voici ma fonction:
```
 function handleSubmit() {
        let data = {
            "cle": "CLE-TEST-IOT",
                "donnees": {
                    "id": mail,
                    "date": date,
                    "urlRelais": url,
                    "message": message
                }
        }
        console.log(data)
        
        const sendData = async () => {
            return await fetch('https://script.google.com/macros/s/AKfycby-TJmFFUFTfiNUbMoSIZx8LVtiskQ-bUt4xO6hmrU0XQpJS8IPUBow/exec', {
                method: 'POST',
                mode: 'no-cors',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(data)
            })
        }
        sendData().then(res => console.log("OK",res)).catch(rej => console.log("FAIL",rej))

    }
```
et ce que je reçois: 
OK
<img width="1644" alt="image" src="https://user-images.githubusercontent.com/75814939/190250910-bb434918-6ffb-4811-81ac-268566898953.png">

Merci :)

**Comment by vincentferraro** [comment]
Bonjour,

j'ai changé le 'Content-type': 'application/json' par 'text/plain' et j'ai reçu cette réponse. Je pense que c'est OK.
<img width="1640" alt="image" src="https://user-images.githubusercontent.com/75814939/190250511-3d1af996-a9e1-4403-bd70-f9a75bbcb6a5.png">

**Comment by KevinHamonApp** [comment]
Oui c'est tout bon, bravo !
