### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by ayoub-mansouri4** [ouivalo/Rejoindre-notre-equipe-tech#3]
## I want to fix this problem
**API doit autoriser CORS(Cross-origin resource sharing) à mon adresse http://localhost:4200 pour accéder aux ressources**

![Screenshot from 2022-09-14 18-04-02](https://user-images.githubusercontent.com/75224501/190467811-155f7aa3-5692-44e7-a9d7-d335461dfcdf.png)

**Comment by KevinHamonApp** [comment]
L'erreur précise que la réponse de preflight n'a rien renvoyé. Autrement dit, une requête OPTIONS a été lancée et n'as pas eu le résultat escompté. Cela peut vouloir dire que votre requête s'est mal adressée
Afin de mieux diagnostiquer votre problème, pouvez-vous indiquer la manière dont vous avez lancé la requête, et préciser les erreurs à partir des requêtes telles que décrites dans l'onglet "NETWORK" de votre navigateur ?

**Comment by ayoub-mansouri4** [comment]
dans mes projets, j'autorise CORS dans la partie back-end(server) pour eviter ce probleme ,en tout cas je vais essayer de régler ce problème .
![Screenshot from 2022-09-15 18-56-53](https://user-images.githubusercontent.com/75224501/190477043-a21d6a7b-82d7-4677-9d1c-46440fc87054.png)

**Comment by KevinHamonApp** [comment]
Si vous ne fournissez pas plus de détails sur la manière dont vous avez lancé la requête, et l'ensemble des erreurs associés, je ne pourrai pas vous aiguiller.

**Comment by ayoub-mansouri4** [comment]
D'abord j'utilise Angular et je veux envoyer la requête post à l'API

voilà  le service 
```
export class CandidatService {
  constructor(public http:HttpClient) { }
  public sendData(json_object:any):Observable<any>{
    return this.http.post<any>("https://script.google.com/macros/s/AKfycby-TJmFFUFTfiNUbMoSIZx8LVtiskQ-bUt4xO6hmrU0XQpJS8IPUBow/exec",json_object);
  }
}
```
voilà le code métier du component
```
export class AppComponent {
  email!:string;
  date!:Date;
  urlGithub!:string;
  message!:string;
  

  constructor(public candidatService:CandidatService){}

  _submit():void{
    let data = {
      "cle":"CLE-TEST-IOT",
          "donnees": {
              "id": this.email,
              "date":this.date,
              "urlRelais":this.urlGithub,
              "message": this.message
          }
   }
    this.candidatService.sendData(data).subscribe(
      (resp:any)=>{console.log(resp)},
      (err:HttpErrorResponse)=>{console.log(err)}
    )
    console.log(data)
  }
}

```

**Comment by KevinHamonApp** [comment]
Bonjour,
Merci pour ces éléments. Je persiste sur le fait que ton problème n'est pas un problème de CORS. Le problème est que ta requête n'atteint pas notre API, et ne reçoit pas de réponse, donc pas d'autorisation CORS de notre part. 
Tu as loupé une indication dans le descriptif Github. Je te laisse le relire pour trouver ce qu'il manque dans ton envoi de requête.
N'hésite pas à revenir vers moi si jamais tu ne la trouve pas.
A bientôt,
Kévin.

**Comment by ayoub-mansouri4** [comment]
Salut monsieur Kévin,
j'ai fait la redirection de ma requête par SPRING BOOT ,c'est à dire que  la requête passe de Angular vers SPRING BOOT (pour éviter le problème de CORS) et puis SPRING BOOT envoie la requête à l'API c'est à dire que j'ai utilisé la consommation des webservices mais à la fin j'ai obtenu une erreur sous forme HTML.
### angular service
```
export class CandidatService {
  constructor(public http:HttpClient) { }
  public sendData(json_object:any):Observable<any>{
    return this.http.post<any>("http://localhost:8080/sendDataToServer",json_object);
  }
}
```
### Spring boot Controller 
```
@RestController
@CrossOrigin(origins = "http://localhost:4200")
public class CandidatController {
    @PostMapping("/sendDataToServer")
    public String sendData(@RequestBody Data data){
        RestTemplate restTemplate = new RestTemplate();
        HttpHeaders headers = new HttpHeaders();
        headers.setAccept(Arrays.asList(MediaType.APPLICATION_JSON));
        String url="https://script.google.com/macros/s/AKfycby-TJmFFUFTfiNUbMoSIZx8LVtiskQ-bUt4xO6hmrU0XQpJS8IPUBow/exec";
        return  restTemplate.exchange(url, HttpMethod.POST, HttpEntity.EMPTY,String.class,data).getBody();

    }
}
```

```
public class Data {
    String cle="CLE-TEST-IOT";
    Donnees donnees=new Donnees();
}
public class Donnees{
    String id;
    String date;
    String urlRelais;
    String message;
}
```

![Screenshot from 2022-09-17 00-33-08](https://user-images.githubusercontent.com/75224501/190832301-4f7aa832-36ca-4560-8f72-2b0fe4262b97.png)

**Comment by ayoub-mansouri4** [comment]
Bonjour Monsieur Kevin,
j'ai résolu le problème .
j'ai fait  la redirection de ma requête HTTP avec Spring boot ,premièrement la requête passe de Angular vers Spring boot (pour éviter le probleme du CORS) et puis Spring boot  envoie la requête à l'API c'est à dire que j'ai utilisé la consommation des webservices avec Spring boot .


## 1er cas :  Postman envoie la requête à Spring boot 
![Screenshot from 2022-09-18 23-49-04](https://user-images.githubusercontent.com/75224501/190931503-9dce3c20-e6f2-4ea4-a0eb-7be8b0be0b60.png)

lorsque je clique sur URL ,j'obtiens ce message 
```
Bravo, ta requête a réussi, et ton petit mot est bien enregistré sur notre base de données ! A bientôt, Kévin pour Ouivalo.
```

## 2eme cas : Angular envoie la requête à Spring boot 
![Screenshot from 2022-09-18 23-01-22](https://user-images.githubusercontent.com/75224501/190930203-484fe6ec-5672-45ea-8eff-6394657a7e61.png)

lorsque je clique sur submit  , j'obtiens une reponse de spring boot qui contient le URL du 1er cas .
 
![Screenshot from 2022-09-19 00-10-25](https://user-images.githubusercontent.com/75224501/190932201-3fdf2f7d-0436-4f58-89ae-a40298b59c42.png)
![Screenshot from 2022-09-19 00-09-54](https://user-images.githubusercontent.com/75224501/190932205-a28b3d8f-a433-44c8-bdc1-b47cb60a35e6.png)


NB: je m'excuse pour la redondance des données dans votre BD car j'ai testé l'application plusieurs fois .
